[window]
padding = { x = 8, y = 5 }
option_as_alt = "OnlyLeft"
decorations_theme_variant = "Dark"

[font]
size = 16
offset = { x = 0, y = 4 }
normal.family = "Iosevka Nerd Font"
normal.style = "Regular"

[colors.primary]
background = '#000000'
foreground = '#FFFFFF'

[colors.normal]
black = '#000000'
red = '#cd0000'
green = '#00cd00'
yellow = '#cdcd00'
blue = '#80a0ff'
magenta = '#cd00cd'
cyan = '#00cdcd'
white = '#e5e5e5'

# Bright colors
[colors.bright]
black = '#7f7f7f'
red = '#ff0000'
green = '#00ff00'
yellow = '#ffff00'
blue = '#5c5cff'
magenta = '#ff00ff'
cyan = '#00ffff'
white = '#ffffff'
